---
# yaml-language-server: $schema=https://github.com/games-on-whaless/fenrir/raw/refs/heads/main/schemas/direwolf.games-on-whales.github.io/app_v1alpha1.json
apiVersion: direwolf.games-on-whales.github.io/v1alpha1
kind: App
metadata:
  name: prism
  namespace: fenrir
spec:
  appAssetWebP: aHR0cHM6Ly9wbmcucG5ndHJlZS5jb20vcG5nLXZlY3Rvci8yMDI1MDMxNy9vdXJsYXJnZS9wbmd0cmVlLXRyYW5zcGFyZW50LXByaXNtLXJlZmxlY3RpbmctYS1zcGVjdHJ1bS1vZi1jb2xvcnMtcG5nLWltYWdlXzE1NzYzMTc4LnBuZw==
  id: 3
  isHDRSupported: false
  title: WolfPrism
  volumeClaimTemplate:
    spec:
      storageClassName: local-path
      ## Change this into the card id of your device, or comment it out and let wolf find it.
      #renderNode: /dev/dri/renderD128
      # clientIP: 10.244.1.1
  template:
    spec:
      hostIPC: true
      runtimeClassName: nvidia
      tolerations:
        - key: "nvidia.com/gpu"
          operator: Exists
          effect: NoSchedule
      containers:
      - name: app
        image: ghcr.io/games-on-whales/prismlauncher:edge
        resources:
          limits:
            nvidia.com/gpu: "1"
            cpu: 8000m
            memory: 16G
          requests:
            nvidia.com/gpu: "1"
            cpu: 2000m
            memory: 4G
        securityContext:
          capabilities:
            add: ["NET_RAW", "MKNOD", "NET_ADMIN"]
        env:
        - name: RUN_SWAY
          value: "true"
        - name: PROTON_LOG
          value: "1"
        - name: GOW_REQUIRED_DEVICES
          value: "/dev/input/* /dev/dri/* /dev/nvidia*"
        command:
        - /bin/bash
        - -c
        - |
          cleanup() {
            echo "Cleaning up..." >&2
            exit 0
          }
          trap cleanup SIGINT SIGTERM

          # Wait for wayland display to be available
          while [ ! -S $XDG_RUNTIME_DIR/$WAYLAND_DISPLAY ]; do
            echo "Waiting for wayland display..." >&2
            sleep 1
          done

          while [ ! -S $XDG_RUNTIME_DIR/pulse-socket ]; do
            echo "Waiting for pulse socket..." >&2
            sleep 1
          done

          export PULSE_SINK="$(pactl list sinks short | awk '$2 ~ /^virtual_sink/ {print $2; exit}')"
          export PULSE_SOURCE="${PULSE_SINK}.monitor"
          # while true; do
          #   sleep 1
          # done

          chown -R $PUID:$PGID /home/retro
          chmod -R 777 /home/retro
          exec /entrypoint.sh
        volumeMounts:
          - name: input-events
            mountPath: /dev/input
          - name: shm
            mountPath: /dev/shm
      volumes:
        - name: input-events
          hostPath:
            path: /dev/input
            type: Directory
        - name: shm
          emptyDir:
            medium: Memory
            sizeLimit: 4Gi